const data = {
  products: [
    {
      name: 'Blue-Eyes White Dragon',
      slug: 'blue-eyes-white-dragon',
      category: 'Normal Monster',
      image: '/images/normalMonster.jpg',
      price: 70,
      brand: 'Nike',
      rating: '4.5',
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Cyber End Dragon',
      slug: 'cyber-end-dragon',
      category: 'Fusion Monster',
      image: '/images/fusionMonster.jpg',
      price: 70,
      brand: 'Nike',
      rating: '5',
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Scarlight Red Dragon Archfiend',
      slug: 'scarlight-red-dragon-archfiend',
      category: 'Synchro Monster',
      image: '/images/synchroMonster.jpg',
      price: 70,
      brand: 'Nike',
      rating: '2',
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Dark Rebellion XYZ Dragon',
      slug: 'dark-rebellion-xyz-dragon',
      category: 'XYZ Monster',
      image: '/images/XYZMonster.jpg',
      price: 70,
      brand: 'Nike',
      rating: '4',
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Odd-Eyes Pendulum Dragon',
      slug: 'odd-eyes-pendulum-dragon',
      category: 'Pendulum Monster',
      image: '/images/pendulumMonster.jpg',
      price: 70,
      brand: 'Nike',
      rating: '5',
      countInStock: 20,
      description: 'A popular pant',
    },
    {
      name: 'Firewall Dragon',
      slug: 'firewall-dragon',
      category: 'Link Monster',
      image: '/images/linkMonster.jpg',
      price: 70,
      brand: 'Nike',
      rating: '5',
      countInStock: 20,
      description: 'A popular pant',
    },
  ],
};

export default data;
