const data = {
  products: [
    {
      name: 'Blue-Eyes White Dragon',
      slug: 'blue-eyes-white-dragon',
      category: 'Normal',
      image: '/images/normalMonster.jpg',
      price: 70,
      cardType: 'Monster',
      rating: '4.5',
      stockCount: 20,
      description: `This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.`,
    },
    {
      name: 'Cyber End Dragon',
      slug: 'cyber-end-dragon',
      category: 'Fusion',
      image: '/images/fusionMonster.jpg',
      price: 70,
      cardType: 'Monster',
      rating: '5',
      countInStock: 20,
      description: `3 Cyber Dragons. A Fusion Summon of this card can only be done with the above Fusion Materials. If this card attacks a Defense Position monster, inflict piercing battle damage.`,
    },
    {
      name: 'Scarlight Red Dragon Archfiend',
      slug: 'scarlight-red-dragon-archfiend',
      category: 'Synchro',
      image: '/images/synchroMonster.jpg',
      price: 70,
      cardType: 'Monster',
      rating: '2',
      countInStock: 20,
      description: `1 Tuner + 1+ non-Tuner monsters.This card's name becomes "Red Dragon Archfiend" while it is on the field or in the GY. Once per turn: You can destroy as many Special Summoned Effect Monsters on the field as possible with ATK less than or equal to this card's (other than this card), then inflict 500 damage to your opponent for each monster destroyed.`,
    },
    {
      name: 'Dark Rebellion XYZ Dragon',
      slug: 'dark-rebellion-xyz-dragon',
      category: 'XYZ',
      image: '/images/XYZMonster.jpg',
      price: 70,
      cardType: 'Monster',
      rating: '4',
      countInStock: 20,
      description: `2 Level 4 monsters. You can detach 2 materials from this card, then target 1 face-up monster your opponent controls; its ATK becomes half its current ATK, and if it does, this card gains that lost ATK.`,
    },
    {
      name: 'Odd-Eyes Pendulum Dragon',
      slug: 'odd-eyes-pendulum-dragon',
      category: 'Pendulum',
      image: '/images/pendulumMonster.jpg',
      price: 70,
      cardType: 'Monster',
      rating: '5',
      countInStock: 20,
      pendulumEffect: `You can reduce the battle damage you take from an attack involving a Pendulum Monster you control to 0. During your End Phase: You can destroy this card, and if you do, add 1 Pendulum Monster with 1500 or less ATK from your Deck to your hand. You can only use each Pendulum Effect of "Odd-Eyes Pendulum Dragon" once per turn.`,
      description: `If this card battles an opponent's monster, any battle damage this card inflicts to your opponent is doubled.`,
    },
    {
      name: 'Firewall Dragon',
      slug: 'firewall-dragon',
      category: 'Link',
      image: '/images/linkMonster.jpg',
      price: 70,
      cardType: 'Monster',
      rating: '5',
      countInStock: 20,
      description: `2+ monsters. Once while face-up on the field (Quick Effect): You can target monsters on the field and/or GY up to the number of monsters co-linked to this card; return them to the hand. If a monster this card points to is destroyed by battle or sent to the GY: You can Special Summon 1 Cyberse monster from your hand. You can only use each effect of "Firewall Dragon" once per turn.`,
    },
  ],
};

export default data;
